// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _GetLocation_HH_
#define _GetLocation_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "GetLocation_dm_detMap_x.h"
#include "GetLocation_dm_detMap_y.h"
#include "GetLocation_dm_detMap_module.h"

namespace ap_rtl {

struct GetLocation : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<16> > agg_result_x;
    sc_out< sc_logic > agg_result_x_ap_vld;
    sc_out< sc_lv<32> > agg_result_y;
    sc_out< sc_logic > agg_result_y_ap_vld;
    sc_out< sc_lv<16> > agg_result_module;
    sc_out< sc_logic > agg_result_module_ap_vld;
    sc_in< sc_lv<16> > tdc_channel;


    // Module declarations
    GetLocation(sc_module_name name);
    SC_HAS_PROCESS(GetLocation);

    ~GetLocation();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    GetLocation_dm_detMap_x* dm_detMap_x_U;
    GetLocation_dm_detMap_y* dm_detMap_y_U;
    GetLocation_dm_detMap_module* dm_detMap_module_U;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_17;
    sc_signal< sc_lv<7> > dm_detMap_x_address0;
    sc_signal< sc_logic > dm_detMap_x_ce0;
    sc_signal< sc_lv<8> > dm_detMap_x_q0;
    sc_signal< sc_lv<7> > dm_detMap_y_address0;
    sc_signal< sc_logic > dm_detMap_y_ce0;
    sc_signal< sc_lv<32> > dm_detMap_y_q0;
    sc_signal< sc_lv<7> > dm_detMap_module_address0;
    sc_signal< sc_logic > dm_detMap_module_ce0;
    sc_signal< sc_lv<1> > dm_detMap_module_q0;
    sc_signal< sc_lv<64> > tmp_fu_92_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_69;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_agg_result_module();
    void thread_agg_result_module_ap_vld();
    void thread_agg_result_x();
    void thread_agg_result_x_ap_vld();
    void thread_agg_result_y();
    void thread_agg_result_y_ap_vld();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_17();
    void thread_ap_sig_69();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_dm_detMap_module_address0();
    void thread_dm_detMap_module_ce0();
    void thread_dm_detMap_x_address0();
    void thread_dm_detMap_x_ce0();
    void thread_dm_detMap_y_address0();
    void thread_dm_detMap_y_ce0();
    void thread_tmp_fu_92_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
